# Generated by Django 4.2.30 on 2026-09-24 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_reset_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='reset_otp_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
