# Generated by Django 4.2.30 on 2026-09-25 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='cashback',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
