# Generated by Django 4.2.30 on 2026-09-25 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_payment_cashback'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='reward_points',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
