# Generated by Django 4.2.30 on 2026-09-25 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_payment_reward_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='credit_score',
            field=models.IntegerField(default=700),
        ),
    ]
