# Generated by Django 4.2.30 on 2026-09-27 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_customuser_credit_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='payment_pin',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
