# Generated by Django 4.2.30 on 2026-09-27 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_customuser_payment_pin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='credit_score',
        ),
    ]
