# Generated by Django 4.2.30 on 2026-09-27 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_remove_customuser_credit_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='credit_score',
            field=models.PositiveIntegerField(default=750),
        ),
    ]
