# Generated by Django 4.2.30 on 2026-10-08 12:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_payment_fraud_prediction_payment_fraud_probability_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskCompliance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk_level', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], default='LOW', max_length=10)),
                ('risk_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('fraud_probability', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('compliance_score', models.DecimalField(decimal_places=2, default=100, max_digits=5)),
                ('aml_status', models.CharField(default='CLEAR', max_length=20)),
                ('transaction_status', models.CharField(default='MONITORED', max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='risk_compliance_records', to='accounts.payment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_compliance_records', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
